packages:
  - packages/*
  - examples/*

allowBuilds:
  esbuild: true
  sharp: true

hoistWorkspacePackages: false

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - sharp

saveWorkspaceProtocol: false
