/**
 * Copyright (c) 2026 Sergio Turolla
 * SPDX-License-Identifier: Apache-2.0
 */

// RMachineConfigError
export const ERR_NO_LOCALES = "ERR_NO_LOCALES";
export const ERR_DUPLICATE_LOCALES = "ERR_DUPLICATE_LOCALES";
export const ERR_INVALID_LOCALE_ID = "ERR_INVALID_LOCALE_ID";
export const ERR_DEFAULT_LOCALE_NOT_IN_LIST = "ERR_DEFAULT_LOCALE_NOT_IN_LIST";

// RMachineConfigError | RMachineUsageError
export const ERR_UNKNOWN_LOCALE = "ERR_UNKNOWN_LOCALE";
export const ERR_INVALID_ARGUMENTS = "ERR_INVALID_ARGUMENTS";
export const ERR_ASYNC_DISPOSE_NOT_SUPPORTED = "ERR_ASYNC_DISPOSE_NOT_SUPPORTED";
export const ERR_NO_LOADER_REGISTERED = "ERR_NO_LOADER_REGISTERED";

// RMachineResolveError
export const ERR_RESOLVE_FAILED = "ERR_RESOLVE_FAILED";
export const ERR_CIRCULAR_DEPENDENCY = "ERR_CIRCULAR_DEPENDENCY";
export const ERR_VERTEX_INSTANCE_NOT_FOUND = "ERR_VERTEX_INSTANCE_NOT_FOUND";
export const ERR_VERTEX_AT_PROCESS_SCOPE = "ERR_VERTEX_AT_PROCESS_SCOPE";
