import { describe, expect, it } from "vitest";
import {
  ERR_FEATURE_REQUIRES_PROXY,
  ERR_INVALID_PATH,
  ERR_INVALID_STRATEGY_CONFIG,
  ERR_LOCALE_BIND_CONFLICT,
  ERR_LOCALE_UNDETERMINED,
  ERR_PATH_ATLAS_MALFORMED,
  ERR_PATH_TRANSLATION_FAILED,
  ERR_SERVER_ONLY,
} from "../../src/errors/error-codes.js";

describe("error codes", () => {
  it.each([
    ["ERR_INVALID_STRATEGY_CONFIG", ERR_INVALID_STRATEGY_CONFIG],
    ["ERR_PATH_ATLAS_MALFORMED", ERR_PATH_ATLAS_MALFORMED],
    ["ERR_SERVER_ONLY", ERR_SERVER_ONLY],
    ["ERR_INVALID_PATH", ERR_INVALID_PATH],
    ["ERR_FEATURE_REQUIRES_PROXY", ERR_FEATURE_REQUIRES_PROXY],
    ["ERR_LOCALE_BIND_CONFLICT", ERR_LOCALE_BIND_CONFLICT],
    ["ERR_LOCALE_UNDETERMINED", ERR_LOCALE_UNDETERMINED],
    ["ERR_PATH_TRANSLATION_FAILED", ERR_PATH_TRANSLATION_FAILED],
  ])("%s should equal its variable name", (expected, actual) => {
    expect(actual).toBe(expected);
  });
});
