#!/usr/bin/env node

/**
 * Writes the rmac package version into src/lib/version.ts so it can
 * be imported at runtime by the CLI. Invoked from the CLI package's
 * sync-version script (and its pre* hooks) via tsx.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Update the CLI version in src/lib/version.ts to match the version in package.json

const __dirname = dirname(fileURLToPath(import.meta.url));
const rmacPackageDir = resolve(__dirname, "..", "packages", "rmac");

const pkg = JSON.parse(readFileSync(resolve(rmacPackageDir, "package.json"), "utf-8")) as {
  version: string;
};

const versionFile = resolve(rmacPackageDir, "src", "lib", "version.ts");
const contents = `// AUTO-GENERATED by pnpm sync-version — do not edit.\n\nexport const CLI_VERSION = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(versionFile, contents);
