// RMachineConfigError
export const ERR_INVALID_STRATEGY_CONFIG = "ERR_INVALID_STRATEGY_CONFIG";
export const ERR_PATH_ATLAS_MALFORMED = "ERR_PATH_ATLAS_MALFORMED";

// RMachineUsageError
export const ERR_SERVER_ONLY = "ERR_SERVER_ONLY";
export const ERR_INVALID_PATH = "ERR_INVALID_PATH";
export const ERR_FEATURE_REQUIRES_PROXY = "ERR_FEATURE_REQUIRES_PROXY";

// RMachineResolveError
export const ERR_LOCALE_BIND_CONFLICT = "ERR_LOCALE_BIND_CONFLICT";
export const ERR_LOCALE_UNDETERMINED = "ERR_LOCALE_UNDETERMINED";
export const ERR_PATH_TRANSLATION_FAILED = "ERR_PATH_TRANSLATION_FAILED";
