export {
  ERR_FEATURE_REQUIRES_PROXY,
  ERR_INVALID_PATH,
  ERR_INVALID_STRATEGY_CONFIG,
  ERR_LOCALE_BIND_CONFLICT,
  ERR_LOCALE_UNDETERMINED,
  ERR_PATH_ATLAS_MALFORMED,
  ERR_PATH_TRANSLATION_FAILED,
  ERR_SERVER_ONLY,
} from "./error-codes.js";
